package com.pinyougou.pojo;

public class TbContentCategory {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_content_category.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_content_category.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_content_category.content_group
     *
     * @mbggenerated
     */
    private String contentGroup;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_content_category.content_key
     *
     * @mbggenerated
     */
    private String contentKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_content_category.status
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_content_category.id
     *
     * @return the value of tb_content_category.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_content_category.id
     *
     * @param id the value for tb_content_category.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_content_category.name
     *
     * @return the value of tb_content_category.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_content_category.name
     *
     * @param name the value for tb_content_category.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_content_category.content_group
     *
     * @return the value of tb_content_category.content_group
     *
     * @mbggenerated
     */
    public String getContentGroup() {
        return contentGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_content_category.content_group
     *
     * @param contentGroup the value for tb_content_category.content_group
     *
     * @mbggenerated
     */
    public void setContentGroup(String contentGroup) {
        this.contentGroup = contentGroup == null ? null : contentGroup.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_content_category.content_key
     *
     * @return the value of tb_content_category.content_key
     *
     * @mbggenerated
     */
    public String getContentKey() {
        return contentKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_content_category.content_key
     *
     * @param contentKey the value for tb_content_category.content_key
     *
     * @mbggenerated
     */
    public void setContentKey(String contentKey) {
        this.contentKey = contentKey == null ? null : contentKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_content_category.status
     *
     * @return the value of tb_content_category.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_content_category.status
     *
     * @param status the value for tb_content_category.status
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }
}